# For Vim
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  " ref: http://blog.monochromegane.com/blog/2013/09/18/ag-and-unite/
  " insert modeで開始
  let g:unite_enable_start_insert = 1
  " 大文字小文字を区別しない
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1
  " agが使える場合は、Unite.vimのgrepでagを使う
  if executable('ag')
    let g:unite_source_grep_command = 'ag'
    let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
    let g:unite_source_grep_recursive_opt = ''
  endif

  " keymap
  nnoremap <silent> <Leader>g  :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
  nnoremap <silent> <Leader>cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
  nnoremap <silent> <Leader>r  :<C-u>UniteResume search-buffer<CR>
  nnoremap <silent> <Leader>b  :<C-u>Unite buffer<CR>
  nnoremap <silent> <Leader>m  :<C-u>Unite mark<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
  let g:vimfiler_as_default_explorer = 1

  " keymap
  nnoremap <silent> <Leader>e :VimFilerExplorer<CR>
'''

[[plugins]]
repo = 'tacroe/unite-mark'
depends = 'unite.vim'
