[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo='mattn/vim-lsp-settings'
depends=['vim-lsp']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends=['asyncomplete']
