set encoding=utf-8
scriptencoding utf-8

filetype plugin indent on
syntax enable

let g:mapleader = "\<Space>"
let g:loaded_2html_plugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logipat = 1
let g:loaded_rrhelper = 1
let g:loaded_spellfile_plugin = 1
let g:loaded_tarPlugin = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zipPlugin = 1
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

let g:netrw_dirhistmax = 0

if &compatible
  set nocompatible
endif
set number
set signcolumn=yes
set numberwidth=8
set laststatus=2
set showcmd
set ruler
set wildmenu
set wildmode=list:longest,full
set showmatch
set matchtime=1
set list
set listchars=tab:¦\ ,trail:･,extends:>,precedes:<
set backspace=indent,eol,start
set title
set whichwrap=b,s,[,],<,>
set nocursorline
set fenc=utf-8
set nobackup
set noswapfile
set novisualbell
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=0
set showtabline=2
set t_Co=256
set mouse=
set incsearch
set hlsearch
if has("termguicolors")
  set termguicolors
endif
set noshowmode
set ignorecase
set smartcase
set autoindent
set lazyredraw
set more
set background=dark

augroup vimrc
  autocmd!
augroup END

augroup vimrc
  autocmd WinEnter * set cursorline
  autocmd WinLeave * set nocursorline
  autocmd InsertEnter * set nocursorline
  autocmd InsertLeave * set cursorline
augroup END

call plug#begin('~/.vim/plugged')
  Plug 'ayu-theme/ayu-vim'
  Plug 'Erichain/vim-monokai-pro'
  Plug 'sainnhe/sonokai'
  Plug 'Mangeshrex/everblush.vim'
  Plug 'tomasiser/vim-code-dark'
  Plug 'patstockwell/vim-monokai-tasty'
  Plug 'mhinz/vim-janah'

  Plug 'sheerun/vim-polyglot'

  Plug 'itchyny/lightline.vim'

  Plug 'editorconfig/editorconfig-vim'

  Plug 'easymotion/vim-easymotion'

  Plug 'airblade/vim-gitgutter'

  Plug 'tpope/vim-repeat'

  Plug 'cohama/lexima.vim'
  Plug 'wellle/targets.vim'
  Plug 'tpope/vim-unimpaired'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-surround'
  Plug 'Matt-A-Bennett/vim-surround-funk'
  Plug 'AndrewRadev/splitjoin.vim'

  Plug 'mhinz/vim-startify'
  Plug 'mhinz/vim-sayonara', { 'on': 'Sayonara' }

  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'mattn/ctrlp-matchfuzzy'
  Plug 'mhinz/vim-grepper', { 'on': ['Grepper', '<plug>(GrepperOperator)'] }

  Plug 't9md/vim-choosewin'
  Plug 'preservim/nerdtree'

  Plug 'mattn/vim-sonictemplate'
  Plug 'mattn/vim-findroot'

  " Plug 'prabirshrestha/asyncomplete.vim'
  " Plug 'prabirshrestha/asyncomplete-buffer.vim'
  " Plug 'akaimo/asyncomplete-around.vim'
  " Plug 'prabirshrestha/asyncomplete-lsp.vim'
  " Plug 'prabirshrestha/vim-lsp'
  " Plug 'mattn/vim-lsp-settings'

  " Plug 'prabirshrestha/quickpick.vim'
  " Plug 'prabirshrestha/quickpick-lsp.vim'

  " Plug 'hrsh7th/vim-vsnip'
  " Plug 'hrsh7th/vim-vsnip-integ'
  " Plug 'rafamadriz/friendly-snippets'

  " " Plug 'vim-denops/denops.vim'
  " " Plug 'Shougo/ddc.vim'
  " " Plug 'Shougo/pum.vim'
  " " Plug 'Shougo/ddc-around'
  " " Plug 'Shougo/ddc-matcher_head'
  " " Plug 'Shougo/ddc-sorter_rank'
  " " Plug 'shun/ddc-vim-lsp'
  " " Plug 'prabirshrestha/vim-lsp'
  " " Plug 'mattn/vim-lsp-settings'
  " " Plug 'matsui54/ddc-buffer'
  " " Plug 'matsui54/denops-popup-preview.vim'

  " Plug 'dense-analysis/ale'
  " " Plug 'vim-syntastic/syntastic'

  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | q | endif

let s:plugs = get(s:, 'plugs', get(g:, 'plugs', {}))
function! FindPlugin(name) abort
  return has_key(s:plugs, a:name) ? isdirectory(s:plugs[a:name].dir) : 0
endfunction
command! -nargs=1 UsePlugin if !FindPlugin(<args>) | finish | endif

runtime! configs/*.vim
