set encoding=utf-8
scriptencoding utf-8

filetype plugin indent on
syntax enable

let g:mapleader = "\<Space>"
let g:loaded_2html_plugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logipat = 1
let g:loaded_rrhelper = 1
let g:loaded_spellfile_plugin = 1
let g:loaded_tarPlugin = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zipPlugin = 1
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

let g:netrw_dirhistmax = 0

if &compatible | set nocompatible | endif
set number
set signcolumn=yes
set numberwidth=8
set laststatus=2
set showcmd
set ruler
set wildmenu
set wildmode=list:longest,full
set showmatch
set matchtime=1
set list
set listchars=tab:¦\ ,trail:･,extends:>,precedes:<
set backspace=indent,eol,start
set title
set whichwrap=b,s,[,],<,>
set nocursorline
set fenc=utf-8
set nobackup
set noswapfile
set novisualbell
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=0
set showtabline=2
set t_Co=256
set mouse=
set incsearch
set hlsearch
if has("termguicolors") | set termguicolors | endif
set noshowmode
set ignorecase
set smartcase
set autoindent
set more
set background=dark
set updatetime=300 timeout timeoutlen=500 ttimeout ttimeoutlen=50 ttyfast
set nolazyredraw

" Language {{{1
let g:PHP_noArrowMatching = 1
let g:PHP_vintage_case_default_indent = 1

" Key mappings {{{1
inoremap jj <Esc>
nnoremap <silent><Esc><Esc> :<C-u>se nohlsearch!<CR>
noremap j gj
noremap k gk
noremap gj j
noremap gk k
noremap <S-j> <Nop>
noremap <S-k> <Nop>
noremap <C-j> 10j
noremap <C-k> 10k
noremap <Leader>n :<C-u>:setl number!<CR>
nnoremap <Leader>s :<C-u>sp<CR>
nnoremap <Leader>v :<C-u>vs<CR>
nnoremap + <C-a>
nnoremap - <C-x>
nnoremap Q <Nop>
if has('terminal') | tnoremap <Esc><Esc> <C-\><C-n> | endif
cnoremap <c-x> <c-r>=expand('%:p')<cr>

command! -bang Q execute("qa<bang>")

" Undo {{{1
if has('persistent_undo')
  let s:undo_dir = expand('~/.cache/vimundo')
  if !isdirectory(s:undo_dir)
    call system('mkdir -p ' . shellescape(s:undo_dir))
  endif
  set undodir=~/.cache/vimundo
  set undofile
endif

" Auto commands {{{1
augroup vimrc
  autocmd!
augroup END

function! s:auto_close_quickfix() abort
  let info = getwininfo(win_getid())[0]

  if info.quickfix && winnr('$') == 1
    quit
  endif
endfunction

autocmd vimrc WinEnter * call s:auto_close_quickfix()

" Toggle cursorline highlight
" autocmd vimrc WinEnter * set cursorline
" autocmd vimrc WinLeave * set nocursorline
" autocmd vimrc InsertEnter * set nocursorline
" autocmd vimrc InsertLeave * set cursorline

" Plugins
runtime! _plugins.vim
