se encoding=utf-8
scriptencoding utf-8

aug MyAutoCmd
  au!
aug END

filetype plugin indent on
syntax enable

let g:mapleader = "\<Space>"

if &compatible
  se nocompatible
en
se number
se signcolumn=number
se numberwidth=8
se laststatus=2
se showcmd
se ruler
se wildmenu
se showmatch
se matchtime=1
se list
se listchars=tab:¦\ ,trail:･,extends:>,precedes:<
se backspace=indent,eol,start
se title
se whichwrap=b,s,[,],<,>
se nocursorline
au InsertLeave * se cursorline!
se fenc=utf-8
se nobackup
se noswapfile
se visualbell
se wildmode=list:longest
se nobackup
se noswapfile
se tabstop=2
se shiftwidth=2
se expandtab
se softtabstop=0
se showtabline=2
se t_Co=256
se mouse=
se incsearch
se hlsearch
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
if has("termguicolors")
  se termguicolors
en
se noshowmode
se background=dark
se ignorecase
se smartcase
se autoindent

call plug#begin('~/.vim/plugged')

Plug 'editorconfig/editorconfig-vim'
Plug 'easymotion/vim-easymotion'
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'mattn/vim-findroot'
Plug 'tpope/vim-repeat'
Plug 'cohama/lexima.vim'
Plug 'wellle/targets.vim'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'Matt-A-Bennett/vim-surround-funk'

Plug 'mhinz/vim-startify'

Plug 't9md/vim-choosewin'

" Plug 'preservim/nerdtree'
" Plug 'justinmk/vim-dirvish'
Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/fern-hijack.vim'

Plug 'sheerun/vim-polyglot'

" Plug 'dense-analysis/ale'

Plug 'vim-denops/denops.vim'

Plug 'Shougo/ddc.vim'
Plug 'Shougo/pum.vim'
Plug 'Shougo/ddc-around'
Plug 'Shougo/ddc-matcher_head'
Plug 'Shougo/ddc-sorter_rank'
Plug 'shun/ddc-vim-lsp'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'matsui54/ddc-buffer'
" Plug 'statiolake/ddc-ale'
" Plug 'matsui54/denops-signature_help'
Plug 'matsui54/denops-popup-preview.vim'

Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'rafamadriz/friendly-snippets'


Plug 'ctrlpvim/ctrlp.vim'
Plug 'mattn/ctrlp-matchfuzzy'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Plug 'prabirshrestha/quickpick.vim'
" Plug 'prabirshrestha/quickpick-lsp.vim'

" Plug 'Shougo/vimproc.vim', { 'do': 'make' }
" Plug 'Shougo/unite.vim'
" Plug 'Shougo/ddu.vim'
" Plug 'Shougo/ddu-ui-ff'
" Plug 'Shougo/ddu-ui-filer'
" Plug 'Shougo/ddu-source-file_rec'
" Plug 'Shougo/ddu-filter-matcher_substring'
" Plug 'Shougo/ddu-kind-file'
" Plug 'shun/ddu-source-buffer'
" Plug 'yuki-yano/ddu-filter-fzf'

Plug 'ayu-theme/ayu-vim'
Plug 'Erichain/vim-monokai-pro'
Plug 'sainnhe/sonokai'
Plug 'Mangeshrex/everblush.vim'
Plug 'tomasiser/vim-code-dark'
Plug 'patstockwell/vim-monokai-tasty'
Plug 'sickill/vim-monokai'
Plug 'tomasr/molokai'

call plug#end()
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | q | endif

" Load configrations
let s:plugs = get(s:, 'plugs', get(g:, 'plugs', {}))
function! FindPlugin(name) abort
  return has_key(s:plugs, a:name) ? isdirectory(s:plugs[a:name].dir) : 0
endfunction
command! -nargs=1 UsePlugin if !FindPlugin(<args>) | finish | endif

runtime! configs/*.vim
